In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

In [5]:
mtcars = pd.read_csv('mt_cars.csv')
mtcars.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [11]:
y = mtcars['cyl'].values

X = mtcars[['mpg', 'hp']].values


In [23]:
knn = KNeighborsClassifier(n_neighbors = 5)
modelo = knn.fit(X,y)

In [24]:
y_pred = modelo.predict(X)
print(y_prev)

[6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 8 8 6]


In [25]:
accuracy = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred, average='weighted')
recall = recall_score(y, y_pred, average='weighted')
f1 = f1_score(y, y_pred, average='weighted')
cm = confusion_matrix(y, y_pred)

print(f'Acurácia: {accuracy}, Precisão: {precision}, Recall: {recall}, F1: {f1}')

Acurácia: 0.90625, Precisão: 0.9161458333333333, Recall: 0.90625, F1: 0.9067887931034483


In [26]:
cm

array([[ 9,  2,  0],
       [ 0,  6,  1],
       [ 0,  0, 14]])

In [27]:
# mpg hp
new_data = np.array([[19.3, 105]])

previsao = modelo.predict(new_data)

distancias, indices = modelo.kneighbors(new_data)
print(distancias)
print(indices)

[[1.2        4.5177428  5.28109837 5.28109837 5.42309875]]
[[ 5 31  1  0  3]]


In [29]:
mtcars.loc[[1,5,31, 0, 3], ["cyl", "mpg", "hp"]]


cyl   mpg   hp
1     6  21.0  110
5     6  18.1  105
31    4  21.4  109
0     6  21.0  110
3     6  21.4  110